name: dev
color: null
values:
  - key: host
    value: ""
    enabled: true
  - key: port
    value: ""
    enabled: true
  - key: baseUrl
    value: ""
    enabled: true
  - key: access_token
    enabled: true
    secret: true
  - key: client-id
    value: ""
    enabled: true
  - key: client-secret
    enabled: true
    secret: true
